projects:
  model:
    schemaPath: src/imports/pie.model.graphql
    extensions:
      endpoints:
        default: "http://localhost:8052"
  logic:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: "http://localhost:8053"
